"""Per-building completion, checker-threshold sensitivity and the clarification split (read-only on every input).

    taskset -c 8-9 env OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 PYTHONNOUSERSITE=1 PYTHONDONTWRITEBYTECODE=1 \
        python analysis/revision/stats/subset_stats.py
Writes per_building.json, tab_per_building.tex, threshold.json, tab_threshold.tex, clarification.json.
"""
import json, sys
sys.dont_write_bytecode = True
sys.path.insert(0, 'analysis/revision/stats')
import numpy as np
from common import *          # noqa: F401,F403

T, S108, S324 = load_tasks()
rows, sets = load_all(T, S108, S324)
CL = {t: T[t]['building_id'] for t in T}
LAB = {k: v[2] for k, v in arm_paths().items()}
BLD = sorted({T[t]['building_id'] for t in T})
SON = 'claude-sonnet-5-5'


def bname(b):
    return b.replace('GNI-project_', 'GNI project ')


def comp(r, ids, t=0.9):
    return float(np.mean([done_at(r[x], t) for x in ids])) if ids else None


# ------------------------------------------------------------------ 2. per building
PB_ARMS = {108: [('ours', (108, 'ours')), ('imitation', (108, 'sft', 'lib')), ('base_note', (108, 'base', 'libnote')),
                 ('base_alone', (108, 'base', 'alone'))] +
                [(f'{mid}_lib', (108, mid, 'lib')) for mid, _, _ in COMMERCIAL] +
                [(f'{mid}_alone', (108, mid, 'alone')) for mid, _, _ in COMMERCIAL],
           324: [('ours', (324, 'ours')), ('imitation', (324, 'sft', 'lib')), ('claude-sonnet-5-5_lib', (324, SON, 'lib')),
                 ('claude-sonnet-5-5_alone', (324, SON, 'alone'))],
           2100: [('ours', (2100, 'ours')), ('imitation', (2100, 'sft')), ('preference', (2100, 'dpo'))]}
pb = {'rule': 'completion = all three axes >= 0.9; one row per held-out building; base measured on the 108 subset only',
      'arms': {str(n): {a: {'source': arm_paths()[k][0].replace(ROOT + '/', ''), 'label': LAB[k]} for a, k in L}
               for n, L in PB_ARMS.items()}, 'buildings': {}}
for b in BLD:
    e = {'versions': sorted({T[t]['ifc_version'] for t in T if CL[t] == b}),
         'origins': sorted({T[t]['origin'] for t in T if CL[t] == b})}
    for n, L in PB_ARMS.items():
        ids = sorted(t for t in sets[n] if CL[t] == b)
        e[str(n)] = {'n': len(ids), **{a: (None if not ids else round(comp(rows[k], ids), 6)) for a, k in L},
                     **{f'{a}_done': int(sum(done(rows[k][t]) for t in ids)) for a, k in L}}
    pb['buildings'][b] = e
# spread summaries
spread = {}
for n, L in PB_ARMS.items():
    for a, _ in L:
        v = [(pb['buildings'][b][str(n)][a], pb['buildings'][b][str(n)]['n'], b) for b in BLD
             if pb['buildings'][b][str(n)]['n']]
        vals = [x[0] for x in v]
        spread[f'{n}/{a}'] = {'min': min(vals), 'min_building': min(v)[2], 'max': max(vals), 'max_building': max(v)[2],
                              'median': float(np.median(vals)), 'sd_between_buildings': round(float(np.std(vals, ddof=1)), 4),
                              'buildings': len(vals)}
pb['spread'] = spread
for n in (108, 324):
    a, bkey = 'ours', f'{SON}_lib'
    d = [(pb['buildings'][x][str(n)][a] - pb['buildings'][x][str(n)][bkey]) for x in BLD if pb['buildings'][x][str(n)]['n']]
    pb[f'final_vs_sonnet_lib_{n}'] = {'buildings_final_higher': sum(1 for x in d if x > 0),
                                      'buildings_equal': sum(1 for x in d if x == 0),
                                      'buildings_sonnet_higher': sum(1 for x in d if x < 0)}
json.dump(pb, open(f'{OUT}/per_building.json', 'w'), indent=1)

# LaTeX: buildings as rows; blocks 108 / 324 / 2,100; bold = highest completion in the row within each task set
cols = [(108, ['ours', 'imitation', 'base_note', f'{SON}_lib']), (324, ['ours', 'imitation', f'{SON}_lib']),
        (2100, ['ours', 'imitation'])]
HEAD = {'ours': 'Final model', 'imitation': 'Imitation', 'base_note': r'\begin{tabular}[b]{@{}c@{}}Untrained,\\library note\end{tabular}',
        f'{SON}_lib': r'\begin{tabular}[b]{@{}c@{}}Claude Sonnet 5.5\\with library\end{tabular}'}


def cells(n, keys, vals):
    best = max(v for v in vals if v is not None)
    out = []
    for v in vals:
        s = '--' if v is None else f3(v)
        out.append(rf'\textbf{{{s}}}' if v is not None and abs(v - best) < 1e-12 else s)
    return out


L = [r'% Generated by analysis/revision/stats/subset_stats.py from per_building.json.',
     r'\begin{table}[htbp]', r'\centering',
     r'\caption{Completion per held-out building on the 108-task subset, the 324-task subset and the 2,100-task '
     r'benchmark. Bold marks the highest completion in each row within each task set.}',
     r'\label{tab:perbuilding}', r'\footnotesize', r'\setlength{\tabcolsep}{3pt}',
     r'\begin{tabular}{@{}l' + 'r' * 5 + 'r' * 4 + 'r' * 3 + r'@{}}', r'\toprule',
     r' & \multicolumn{5}{c}{108-task subset} & \multicolumn{4}{c}{324-task subset} & \multicolumn{3}{c}{2,100-task benchmark} \\',
     r'\cmidrule(lr){2-6}\cmidrule(lr){7-10}\cmidrule(l){11-13}',
     'Building & Tasks & ' + ' & '.join(HEAD[k] for k in cols[0][1]) + ' & Tasks & ' +
     ' & '.join(HEAD[k] for k in cols[1][1]) + ' & Tasks & ' + ' & '.join(HEAD[k] for k in cols[2][1]) + r' \\',
     r'\midrule']
for b in BLD + ['ALL']:
    parts = [bname(b) if b != 'ALL' else 'All buildings']
    for n, keys in cols:
        if b == 'ALL':
            ids = sorted(sets[n])
            vals = [comp(rows[dict(PB_ARMS[n])[k]], ids) for k in keys]
            nn = len(ids)
        else:
            e = pb['buildings'][b][str(n)]
            nn = e['n']
            vals = [e[k] if nn else None for k in keys]
        parts += [f'{nn:,}' if nn else '0'] + (cells(n, keys, vals) if nn else ['--'] * len(keys))
    if b == 'ALL':
        L.append(r'\midrule')
    L.append(' & '.join(parts) + r' \\')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
open(f'{OUT}/tab_per_building.tex', 'w').write('\n'.join(L))

# ------------------------------------------------------------------ 3. threshold sensitivity
TH = [0.85, 0.90, 0.95, 0.98]
TH_ARMS = {108: [(108, 'ours'), (108, 'sft', 'lib'), (108, 'sft', 'alone'), (108, 'dpo', 'lib'), (108, 'base', 'alone'),
                 (108, 'base', 'libnote')] + [(108, mid, a) for mid, _, _ in COMMERCIAL for a in ('alone', 'lib')],
           324: [(324, 'ours'), (324, 'sft', 'lib'), (324, 'sft', 'alone'), (324, 'prev', 'lib'), (324, SON, 'alone'),
                 (324, SON, 'lib')],
           2100: [(2100, 'sft'), (2100, 'dpo'), (2100, 'ours'), (2100, 'prev'), (2100, 'sft_small'), (2100, 'dpo_small'),
                  (2100, 'grpo_small')]}
th = {'verdict_rule': 'a task counts as completed at threshold t when geometry, semantics and topology are each >= t '
                      '(per-task score axes as stored). At t = 0.9 this is make_results_exhibits.done(). The stored '
                      "score 'final' is the equal-weight mean (g + s + t) / 3 (code/modifc_score/scorer.py lines 373-377, "
                      'config.py weights 1/1/1) and is not the verdict; underspecified tasks carry one value 0 or 1 on '
                      'all three axes (scorer.py underspecified_mode), so their verdict does not move with t.',
      'thresholds': TH, 'arms': {}, 'paired': {}, 'binding_axis_at_0_98': {}}
for n, keys in TH_ARMS.items():
    ids = sorted(sets[n])
    for k in keys:
        th['arms']['|'.join(map(str, k))] = {'set': n, 'label': LAB[k], 'source': arm_paths()[k][0].replace(ROOT + '/', ''),
                                             **{f'{t:.2f}': {'completion': round(comp(rows[k], ids, t), 6),
                                                             'done': int(sum(done_at(rows[k][x], t) for x in ids))}
                                                for t in TH}}
for n, a, b in ((108, (108, 'ours'), (108, SON, 'lib')), (324, (324, 'ours'), (324, SON, 'lib')),
                (108, (108, 'ours'), (108, SON, 'alone')), (2100, (2100, 'ours'), (2100, 'sft'))):
    ids = sorted(sets[n])
    key = f'{n}: {LAB[a]} minus {LAB[b]}'
    th['paired'][key] = {}
    for t in TH:
        d = [done_at(rows[a][x], t) - done_at(rows[b][x], t) for x in ids]
        tb, cb = boot(d), cboot(d, ids, CL)
        th['paired'][key][f'{t:.2f}'] = {'diff': round(tb[0], 4), 'task_level': [round(tb[1], 4), round(tb[2], 4)],
                                         'cluster': [round(cb[1], 4), round(cb[2], 4)],
                                         'a_only': sum(1 for x in d if x > 0), 'b_only': sum(1 for x in d if x < 0)}
for k in ((2100, 'ours'), (108, 'ours'), (108, SON, 'lib'), (324, SON, 'lib')):
    ids = sorted(sets[k[0]])
    c = {'geometry': 0, 'semantics': 0, 'topology': 0}
    nfail = 0
    for x in ids:
        ax = axes(rows[k][x])
        if min(ax) >= 0.9 and min(ax) < 0.98:
            nfail += 1
            for nm, v in zip(('geometry', 'semantics', 'topology'), ax):
                c[nm] += v < 0.98
    th['binding_axis_at_0_98']['|'.join(map(str, k))] = {
        'completed_at_0.90_not_at_0.98': nfail, 'axis_below_0.98_among_them': c}
json.dump(th, open(f'{OUT}/threshold.json', 'w'), indent=1)

ROWLAB = {(108, 'ours'): 'Final model, with library', (108, 'sft', 'lib'): 'Imitation, with library',
          (108, 'sft', 'alone'): 'Imitation, alone', (108, 'dpo', 'lib'): 'Preference stage, with library',
          (108, 'base', 'alone'): 'Untrained, alone', (108, 'base', 'libnote'): 'Untrained, library note'}
for mid, nm, _ in COMMERCIAL:
    ROWLAB[(108, mid, 'alone')] = f'{nm}, alone'
    ROWLAB[(108, mid, 'lib')] = f'{nm}, with library'
ROWLAB.update({(2100, 'sft'): 'Imitation', (2100, 'dpo'): 'Preference stage', (2100, 'ours'): 'Final model',
               (2100, 'prev'): 'Earlier corpus', (2100, 'sft_small'): 'Ten buildings, imitation',
               (2100, 'dpo_small'): 'Ten buildings, preference stage',
               (2100, 'grpo_small'): 'Ten buildings, reinforcement'})


def block(n, keys, title):
    out = [rf'\multicolumn{{5}}{{@{{}}l}}{{\textit{{{title}}}}} \\']
    vals = {k: [th['arms']['|'.join(map(str, k))][f'{t:.2f}']['completion'] for t in TH] for k in keys}
    best = [max(vals[k][i] for k in keys) for i in range(len(TH))]
    for k in keys:
        out.append(' & '.join([ROWLAB[k]] + [rf'\textbf{{{f3(v)}}}' if abs(v - best[i]) < 1e-12 else f3(v)
                                              for i, v in enumerate(vals[k])]) + r' \\')
    return out


def sgn(x):
    return ('+' if x >= 0 else '$-$') + f'{abs(x):.3f}'


L = [r'% Generated by analysis/revision/stats/subset_stats.py from threshold.json.',
     r'\begin{table}[htbp]', r'\centering',
     r'\caption{Completion when every score axis must reach the threshold $t$. Bold marks the highest completion '
     r'in each column within each task set.}', r'\label{tab:threshold}', r'\footnotesize',
     r'\setlength{\tabcolsep}{5pt}', r'\begin{tabular}{@{}lcccc@{}}', r'\toprule',
     'Model and arm & ' + ' & '.join(f'$t={t:.2f}$' for t in TH) + r' \\', r'\midrule']
L += block(108, TH_ARMS[108], '108-task subset')
L.append(r'\midrule')
L += block(2100, TH_ARMS[2100][:4], '2,100-task benchmark')
L.append(r'\midrule')
pk = f'108: {LAB[(108, "ours")]} minus {LAB[(108, SON, "lib")]}'
L.append(r'\multicolumn{5}{@{}l}{\textit{Final model minus Claude Sonnet 5.5 with library, 108-task subset}} \\')
L.append(' & '.join(['Paired difference'] + [sgn(th['paired'][pk][f'{t:.2f}']['diff']) for t in TH]) + r' \\')
L.append(' & '.join(['Building-level 95\\,\\% interval'] +
                    [f"[{sgn(th['paired'][pk][f'{t:.2f}']['cluster'][0])}, {sgn(th['paired'][pk][f'{t:.2f}']['cluster'][1])}]"
                     for t in TH]) + r' \\')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
open(f'{OUT}/tab_threshold.tex', 'w').write('\n'.join(L))

# ------------------------------------------------------------------ 4. clarification (underspecified) tasks
UND = {t for t in T if 'wording.underspecified' in (T[t]['families'] or [])}
assert UND == {t for t in T if T[t]['clarification']} and len(UND) == 156
cl = {'definition': "task families contain 'wording.underspecified' (equal to a non-empty 'clarification' field); "
                    'the expected answer is no edit and a question back', 'n_benchmark': len(UND),
      'per_part': {v: sum(1 for t in UND if T[t]['ifc_version'] == v) for v in VERS}, 'arms': {}, 'paired': {}}
for k in arm_paths():
    n = k[0]
    ids = sorted(sets[n])
    u = [t for t in ids if t in UND]
    o = [t for t in ids if t not in UND]
    cl['arms']['|'.join(map(str, k))] = {
        'set': n, 'label': LAB[k], 'n': len(ids), 'n_underspecified': len(u),
        'share_underspecified': round(len(u) / len(ids), 4),
        'completion_all': round(comp(rows[k], ids), 4), 'completion_underspecified': round(comp(rows[k], u), 4),
        'done_underspecified': int(sum(done(rows[k][t]) for t in u)),
        'completion_rest': round(comp(rows[k], o), 4), 'done_rest': int(sum(done(rows[k][t]) for t in o)),
        'n_rest': len(o)}
for n, a, b in ((108, (108, 'ours'), (108, SON, 'lib')), (324, (324, 'ours'), (324, SON, 'lib')),
                (108, (108, 'ours'), (108, SON, 'alone')), (324, (324, 'ours'), (324, SON, 'alone')),
                (2100, (2100, 'ours'), (2100, 'sft'))):
    key = f'{n}: {LAB[a]} minus {LAB[b]}'
    cl['paired'][key] = {}
    for part, sel in (('all', lambda t: True), ('without_underspecified', lambda t: t not in UND),
                      ('underspecified_only', lambda t: t in UND)):
        ids = sorted(t for t in sets[n] if sel(t))
        d = [done(rows[a][x]) - done(rows[b][x]) for x in ids]
        tb, cb = boot(d), cboot(d, ids, CL)
        cl['paired'][key][part] = {'n': len(ids), 'diff': round(tb[0], 4), 'task_level': [round(tb[1], 4), round(tb[2], 4)],
                                   'cluster': [round(cb[1], 4), round(cb[2], 4)], 'n_buildings': cb[3]}
json.dump(cl, open(f'{OUT}/clarification.json', 'w'), indent=1)
print('per_building, threshold, clarification written')
